### ISSUE TITLE
No information about the club's location, your contact on telegram, etc.

### ISSUE THREAD

**Issue by Riven-Spell** [lwhs-compsci/intro#1]
Title describes the issue pretty much on point.

**Comment by andrew-pa** [comment]
1) Lake Washington High School? Need I say more on the location?
2) I figured that we would add people only who we had contact with physically. If you want though, I will add you. Talk to me on qxczv.pw.

**Comment by Riven-Spell** [comment]
What time? What room?

**Comment by andrew-pa** [comment]
Resolved.
